---
- name: Creates backend directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: copy artifact.tar.gz
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
- name: install curl
  apt:
    name:
      - curl
    update_cache: yes
    cache_valid_time: 3600
  become: True

- name: get url
  shell: |
      curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
  become: True


- name: install node
  apt:
    name:
      - nodejs
    update_cache: yes
    cache_valid_time: 3600
  become: True

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start the app
  shell: |
      cd /home/ubuntu/backend
      npm install
      npm audit fix 
      pm2 list && ps aux|grep node
      pm2 stop default
      pm2 start npm -- run start
  become: True
