---
- name: Print env variable
   shell: echo $PATH
   register: print_result

 - name: print message
   debug:
     msg: "{{ print_result.stdout_lines }}"

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy artifact.tar.gz file
  template:
    src: "files/artifact.tar.gz"
    dest: "/home/ubuntu/backend/artifact.tar.gz"

- name: Install Node Dependencies
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Building backend service
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Running backend service
  shell: |
    cd /home/ubuntu/backend    
    pm2 start npm --no-automation --name "backend" -- run start