---
- name: "update packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start backend
  shell:  |
    /usr/bin/pm2 start /home/ubuntu/app/dist/main.js --name backend -f
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ~/src/migrations
    TYPEORM_MIGRATIONS: ~/src/migrations/*.ts
    TYPEORM_ENTITIES: ~/src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople.crvxyau4u1vo.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: mypassword
    TYPEORM_DATABASE: postgres