version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            # Your code here
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
     - image: cimg/node:18.7.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Run frontend test
          command: |
          # Your code here
          cd frontend
          npm install
          npm run test
      - save_cache:
          paths: [ frontend/node_modules ]
          key: frontend-build

  test-backend:
    docker:
      - image: cimg/node:18.7.0
    # Docker image here
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Run backend test
          command: |
          # Your job code here
            cd backend
            npm install
            npm run test
    # Restore from cache
      - restore_cache:
          paths: [backend/node_modules]
          key: backend- backend


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          required: [build-frontend]
      - test-backend:
          required: [build-backend]